### ISSUE TITLE
Color maps could look better

### ISSUE THREAD

**Issue by lee1043** [UV-CDAT/vcs#238]
![colormaps_uvcdat2 10_jiwoolee_20170823](https://user-images.githubusercontent.com/17091564/29690086-62f64164-88da-11e7-8ebd-562c39ea2001.png)

Some of color maps have discrete colors at both edges. Instead of using ```range(16,240)``` for ```vcs.getcolors``` to avoid those edge colors, I think it would be much simple for users if we can make users no need to think about it.  

Below code is for making above image. 

```python
# Grep all available color maps and visualize them
# 2017. 8. Jiwoo Lee Created

import cdms2 as cdms
import vcs
import MV2
import numpy as np
import EzTemplate

a=[]

num_levels = 100

for i in range(0,num_levels):
  a.append(i/float(num_levels))

for i in range(0,num_levels):
  a.append(i/float(num_levels))

a = MV2.array(a)
a = MV2.reshape(a, (-1,num_levels))

v = vcs.init(geometry={"width":600,"height":1200}, bg=1)

cmlst = v.listelements('colormap')

cmlst_num = len(cmlst)
print len(cmlst)

#cmlst_num = 30 ## debug... 

T = vcs.createtemplate()
T.blank(['title','mean','min','max','dataname','crdate','crtime',
         'units','zvalue','tvalue','xunits','yunits','xname','yname', 'legend'])

M = EzTemplate.Multi(template=T, rows=cmlst_num, columns=1)
M.margins.top = 0.05
M.margins.bottom = 0.05
M.margins.left = 0.3
M.margins.right = 0.05
M.spacing.vertical= 0.005

plot_title = v.createtext()
plot_title.string = 'UVCDAT 2.10 Colormaps'
plot_title.height = 15
plot_title.halign = 'center'
plot_title.valign = 'bottom'
plot_title.x = 0.5
plot_title.y = 1 - M.margins.top + (0.01)
v.plot(plot_title, T)

for i in range(0, cmlst_num):
  box = v.createboxfill()
  box.xticlabels('','') # Hide x-axis tick labels
  box.yticlabels('','') # Hide y-axis tick labels
  box.colormap = cmlst[i]
  t = M.get(row=i, column=0, legend='none')
  t.blank(['legend'])
  v.plot(a, t, box, bg=1)
  cm_name = cmlst[i]

  subplot_title = vcs.createtext()
  subplot_title.string = cm_name
  subplot_title.x = 0.01
  subplot_title.y = (t.box1.y1 + t.box1.y2) / 2.
  subplot_title.height = 10
  subplot_title.halign = 'left'
  subplot_title.valign = 'half'
  subplot_title.color = 'black'
  v.plot(subplot_title, t)

  v.removeobject(box)
  v.removeobject(subplot_title)
  print cm_name

v.png('Colormaps_uvcdat2.10.png')
```

**Comment by doutriaux1** [comment]
@lee1043 in order to have vcs revert to the `old` behaviour (range(16,240) simply add:
```python
vcs.utils.defaultColorsRange = range(16,240)
```
At the begining of your script that should solve the issue for you

**Comment by durack1** [comment]
@lee1043 this is great, thanks for kicking this off.. I've been begging for this for a while UV-CDAT/uvcdat#906

There seems to be quite a large number of dupes in the https://github.com/UV-CDAT/vcs/issues/238#issue-252744867 above, so `blue2green == blue_to_grn`, `blue2grey == blue_to_grey` etc etc..

It also seems to be missing a large number of the palettes that @chaosphere2112 managed to find back in https://github.com/UV-CDAT/uvcdat/issues/1345#issuecomment-162099427, from @chaosphere2112's stuff, I also noted how many unique matplotlib colormaps were available, see https://github.com/UV-CDAT/uvcdat/issues/1345#issuecomment-161110687, plus all the additional colormaps that I provided through to @chaosphere2112 in https://github.com/UV-CDAT/uvcdat/issues/1345#issuecomment-162099427 (the bottom right thicker panels) which can be found in the file https://github.com/durack1/durolib/blob/master/lib/colourLib.py

Happy to iterate and tweak these alongside you..

And so we have everything in one place..

The matplotlib colormaps:
![](http://matplotlib.org/1.2.1/_images/show_colormaps.png)
And the @chaosphere2112 maps from Dec 2015
![colormaps](https://cloud.githubusercontent.com/assets/718512/11602854/7e19da10-9a92-11e5-9428-6db44505e7f5.png)

**Comment by jypeter** [comment]
Thanks @lee1043 for the useful script! Some version of it would be useful in the gallery

Several color related questions for @doutriaux1 et al:
- do we still have something like the old `x.colormapgui()`? Or some kind of widget that would allow the user to browse the existing colormaps?
- I had never heard of `x.util.*`, eventhough some of the functions in there look familiar. Is this documented somewhere? I have failed to find something about this (and something recent about colormaps) in the uvcdat web site. Of course, the fact that there is no Search button did not help :( https://github.com/UV-CDAT/uvcdat-site/issues/129
- Is there an easy way to _revert the order of colors in a colormap_? eg I want ''rainbownogreen" for temperature and I need it in blue to red order?
- One of the major vcs limitations in the good old cgm/gks days (when plotting was easier and faster) was that you could only use 256 colors at a given time on a canvas, and I had to do a lot of custom colormaps generation. Is it possible now to _use different colormaps_ for different plots on the **same** canvas

I have recently heard about a useful set of colormaps, with a matching nice documentation: http://matplotlib.org/cmocean/

**Comment by doutriaux1** [comment]
* @jypeter colormapgui() is dead, in the process of being re-implemented in vcdat
* @jypeter good point about `vcs.utils`, I will create an issue to make a jupyter notebook about it. readthedocs eventually will have it as well.
* just pass the reverted colors to the graphics method, example:
```python
import vcs
gm = vcs.createisofill()
gm.colormap = "rainbow"
levels = [1,2,3,4,5]
colors = vcs.getcolors(levels,colors=range(255,-1,-1))
gm.fillareacolors=colors
```
* as demonstrated above, each graphic method can now have its own colormap, the colormap used is decide in this order: graphic_method -> canvas -> vcs module

```python
import vcs
x=vcs.init()
gm=vcs.createisofill()
# First way setting colormap at vcs level
vcs._colorMap = "viridis"
# Second way at the canvas level
x.setcolormap("inferno")  # superseeds vcs colormap
# Third way at gm level
gm.colormap = "plasma"  # superseeds canvas
```

**Comment by lee1043** [comment]
@doutriaux1 Color shrinking for some horizontal bars is not dependent to selection of color map. See below. Should be something related to EzTemplate? Weird...

![colormaps_uvcdat2 10](https://user-images.githubusercontent.com/17091564/29795832-c86c387a-8c02-11e7-9955-4a8c6eba4f41.png)


```python
import cdms2 as cdms
import vcs
import MV2
import numpy as np
import EzTemplate

vcs.utils.defaultColorsRange = range(16,240)

a=[]

num_levels = 100

for i in range(0,num_levels):
  a.append(i/float(num_levels))

for i in range(0,num_levels):
  a.append(i/float(num_levels))

a = MV2.array(a)
a = MV2.reshape(a, (-1,num_levels))

v = vcs.init(geometry={"width":600,"height":1200}, bg=1)

cmlst = v.listelements('colormap')

cmlst_num = len(cmlst)
print len(cmlst)

#cmlst_num = 30 ## debug... 

T = vcs.createtemplate()
T.blank(['title','mean','min','max','dataname','crdate','crtime',
         'units','zvalue','tvalue','xunits','yunits','xname','yname', 'legend'])

M = EzTemplate.Multi(template=T, rows=cmlst_num, columns=1)
M.margins.top = 0.05
M.margins.bottom = 0.05
M.margins.left = 0.3
M.margins.right = 0.05
M.spacing.vertical= 0.005

plot_title = v.createtext()
plot_title.string = 'UVCDAT 2.10 Colormaps'
plot_title.height = 15
plot_title.halign = 'center'
plot_title.valign = 'bottom'
plot_title.x = 0.5
plot_title.y = 1 - M.margins.top + (0.01)
v.plot(plot_title, T)

for i in range(0, cmlst_num):
#for i in range(0, 4):
#for i in range(cmlst_num-1, 2, -1):
  box = v.createboxfill()
  box.color_1 = 16
  box.color_2 = 240
  #box.boxfill_type = 'custom'
  box.xticlabels('','') # Hide x-axis tick labels
  box.yticlabels('','') # Hide y-axis tick labels
  #box.colormap = cmlst[i]
  box.colormap = 'default'  #### JUST FOR TEST....

  t = M.get(row=i, column=0, legend='none')
  #t = M.get(row=cmlst_num-i, column=0, legend='none')
  t.blank(['legend'])

  print a.min(), a.max(), t.data.x1, t.data.x2
  #v.plot(a.filled(), t, box, bg=1)
  v.plot(a, t, box, bg=1)

  subplot_title = vcs.createtext()
  subplot_title.string = box.colormap
  subplot_title.x = 0.01
  subplot_title.y = (t.box1.y1 + t.box1.y2) / 2.
  subplot_title.height = 10
  subplot_title.halign = 'left'
  subplot_title.valign = 'half'
  subplot_title.color = 'black'
  v.plot(subplot_title, t)

  v.removeobject(box)
  v.removeobject(subplot_title)
  print box.colormap

v.png('Colormaps_uvcdat2.10.png')
```

**Comment by doutriaux1** [comment]
@lee1043 I think so, something in EzTemplate, althoguh template.data.x1 and template.data.x2 are constant. Sorry didn't have time to look at it yet.

**Comment by lee1043** [comment]
@durack1 @doutriaux1 @chaosphere2112 

Maybe having matplotlib color maps in VCS related to ```python vcs.colors.matplotlib2vcs```?

https://uvcdat.llnl.gov/docs/vcs/misc/colors.html
https://uvcdat.llnl.gov/docs/_modules/vcs/colors.html

I will test it. Any comment welcome.

**Comment by lee1043** [comment]
I believe below is what @chaosphere2112 was working on at https://github.com/UV-CDAT/uvcdat/issues/1345#issuecomment-162099427. Could use ```vcs.colors.matplotlib2vcs``` to get all available color maps from matplotlib.

![colormaps_matplotlib_vcs](https://user-images.githubusercontent.com/17091564/29797581-d434616e-8c0c-11e7-8768-2f6b33f57887.png)

```python
# Grep all available color maps and visualize them
# 2017. 8. Jiwoo Lee Created

import cdms2 as cdms
import vcs
import MV2
import numpy as np
import EzTemplate
import matplotlib.pyplot as plt

#vcs.utils.defaultColorsRange = range(16,240)

a=[]

num_levels = 100

for i in range(0,num_levels):
  a.append(i/float(num_levels))

for i in range(0,num_levels):
  a.append(i/float(num_levels))

a = MV2.array(a)
a = MV2.reshape(a, (-1,num_levels))

v = vcs.init(geometry={"width":600,"height":2400}, bg=1)

# Get list of all available colormaps from matplotlib (except '_r' which is reversed one)
cmlst = [x for x in plt.colormaps() if not '_r' in x]
cmlst = sorted(cmlst, key=lambda s: s.lower()) # Case insensitive alphabet order

cmlst_num = len(cmlst)
print len(cmlst)

T = vcs.createtemplate()
T.blank(['title','mean','min','max','dataname','crdate','crtime',
         'units','zvalue','tvalue','xunits','yunits','xname','yname', 'legend'])

M = EzTemplate.Multi(template=T, rows=cmlst_num, columns=1)
M.margins.top = 0.05 / 2.
M.margins.bottom = 0.05
M.margins.left = 0.3
M.margins.right = 0.05
M.spacing.vertical= 0.005 / 2.

plot_title = v.createtext()
plot_title.string = 'Matplotlib Colormaps for VCS'
plot_title.height = 15 / 2.
plot_title.halign = 'center'
plot_title.valign = 'bottom'
plot_title.x = 0.5
plot_title.y = 1 - M.margins.top + (0.01)
v.plot(plot_title, T)

for i in range(0, cmlst_num):
    box = v.createboxfill()
    #box.color_1 = 16
    #box.color_2 = 240
    #box.boxfill_type = 'custom'
    box.xticlabels('','') # Hide x-axis tick labels
    box.yticlabels('','') # Hide y-axis tick labels
    box.colormap = vcs.colors.matplotlib2vcs(cmlst[i])

    t = M.get(row=i, column=0, legend='none')
    t.blank(['legend'])

    v.plot(a, t, box, bg=1)

    subplot_title = vcs.createtext()
    #subplot_title.string = box.colormap
    subplot_title.string = cmlst[i].encode('ascii')
    subplot_title.x = 0.01
    subplot_title.y = (t.box1.y1 + t.box1.y2) / 2.
    subplot_title.height = 10 / 2.
    subplot_title.halign = 'left'
    subplot_title.valign = 'half'
    subplot_title.color = 'black'
    v.plot(subplot_title, t)

    v.removeobject(box)
    v.removeobject(subplot_title)
    print box.colormap

v.png('Colormaps_matplotlib_VCS.png')
v.clear()
```

**Comment by durack1** [comment]
@lee1043 I know that if you put a trailing `_r` on the matplotlib colormaps (so e.g. `RdBu_r`) you get the inverted colormap in this case the inverse of `RdBu` just FYI, I **think** this works for most colormaps

**Comment by doutriaux1** [comment]
@lee1043 I worte the code to convert mpl colormap so yes you can import mpl colormap. Not sure the `_r` trick will work though, it might be at plotting time kind of trick. Personally I still don't see the usefullness on having an inverted colormap when all you need to do is colors[::-1] once you got your colors...

**Comment by lee1043** [comment]
@durack1 @doutriaux1 I can load ```_r``` color maps from matplotlib and convert them to VCS as like they are independent color maps. Just didn't listed them on the image to avoid image becomes very long in vertical.

**Comment by lee1043** [comment]
@doutriaux1 @durack1  friendly reminder: it would be nice if we can have matplotlib colormaps already in it when vcs is imported and initialized.

**Comment by taylor13** [comment]
Below are some sample figures from the set I produced for the IPCC AR4.  Some of these color bars are pretty good I think.  I'll also include the color table and the code used to produce these plots.  (scroll down)
![pr_obs](https://user-images.githubusercontent.com/4993439/29949136-81b74174-8e67-11e7-9b91-dab5a1734f64.jpg)
![rlut_page_1_diff](https://user-images.githubusercontent.com/4993439/29949315-b3c0d95e-8e68-11e7-9cf0-48fca4774065.jpg)
![tasm_page_1_diff](https://user-images.githubusercontent.com/4993439/29949317-b3c150a0-8e68-11e7-8aaf-c9cb0d22bfe9.jpg)
![tasm_mean_diff](https://user-images.githubusercontent.com/4993439/29949316-b3c0d53a-8e68-11e7-83c8-e13198378fa9.jpg)
![tasm_obs](https://user-images.githubusercontent.com/4993439/29949318-b3c1910a-8e68-11e7-95cc-2d6d61defb2c.jpg)
![pr_page_1_diff](https://user-images.githubusercontent.com/4993439/29949319-b3c1b022-8e68-11e7-8397-09c89732289b.jpg)
Here's the code:
```
import cdms,vcs,sys,cdtime,os,MV,genutil,cdutil
sys.path.append('../../misc')
from common import *
from Plotter import Multi
## sys.path.append('/work/pcmdi/amip/misc')
import dictionaries
#struct.root='/work/pcmdi/ipcc/4th/Ocean/maps/Data/'
var2=None
continents=2
var='tasmax'
## var2='tasmin' # Set to None for no difference
## title2='Daily Temperature Spread (Max-Min) '

## var2='rsut'
## title2 = 'Shortwave Cloud Radiative Forcing '
## var2='rlut'
## title2 = 'Longwave Cloud Radiative Forcing '

var='so'
var='dtr'
var='tasm'
var='rsut'
var='pr'
var='rlutcs'
var='rsutcs'
var='rsut'
var='ts'
## var='tasm'

var='so'

contourlines=True
mask_threshold=False
diff=True

stat=None
# stat='correl'  # Compute correl 
# stat='std'  # Compute standard deviation over months


masklnd= False
masklnd= True
obs_clim=True

# snm='MAM'
snm=''  # annual mean

if stat is not None: snm=''

if not diff: contourlines=False
ref = 'reference'
struct=struct_ac2

offset = 0.

if var=='so':
    struct=struct_ac
    struct.start='1950'
elif var=='rsut' or var=='rsutcs' or var=='rlut' or var=='rlutcs':
    obs_clim=True
elif var=='tauu' or var=='pr':
    ref='reference3'
elif var=='ts':
    ref='reference3'
    offset = -273.15
elif var=='tasm':
    offset = -273.15
continent_line=1

if diff:
    diff_offset=0.
else:
    diff_offset=offset

struct.exp='20c3m'
struct.fqcy='mo'
struct.region='atm'
struct.run='1'
struct.var=var
struct.extension='nc'

if struct.var=='so':
    continents=0
    struct.region='ocn'
    struct.root='/pcmdi/doutriau/ipcc/data'
elif struct.var=='dtr':
    continents=0
    struct.root='/data/IPCC/pcmdi/ipcc/data'
elif struct.var=='tasm':
##     struct.root='/pcmdi/doutriau/ipcc/data'
    struct.root='/home/ktaylor/ipcc/data'
##     masklnd= False
elif struct.var=='tasmax':
##     struct.root='/pcmdi/doutriau/ipcc/data'
    masklnd= False
elif struct.var=='ts':
    continents=0
    masklnd=True
    mask_threshold = [273.15,-1] # value, and indicator for less than

colors = range(144,156)
dcolors=colors
ecolors=colors


user_spec_levels=False
contourlevs=None
if var2=='tasmin':
    user_spec_levels=True
    if stat=='std':
        ulevels=[-1.e20,-5,-4,-3,-2,-1,0,1,2,3,4,5,1.e20]
        ulevelsobs=[0,1,2,3,4,5,6,7,8,9,10,11,1.e20]
        ulevelserr= [0.,.5,1.,1.5,2.,2.5,3.,3.5,4.,4.5,5.,5.5,1.E20]
    else:
        ulevels = [-1.e20,-5,-4,-3,-2,-1,0,1,2,3,4,5,1.e20]
        ulevelsobs = [0,1,2,3,4,5,6,7,8,9,10,11,1.e20]
        ulevelserr= [0.,.5,1.,1.5,2.,2.5,3.,3.5,4.,4.5,5.,5.5,1.E20]

elif struct.var=='tasm':
    user_spec_levels=True
    if stat=='std':
        ulevels= [-1.e20,-2.5, -2., -1.5, -1., -.5, 0., .5, 1., 1.5, 2., 2.5, 1.e20]
        contourlevs=[0.,2., 4., 6., 8., 10., 12., 14., 16., 18., 20., 22., 24.]
        ulevelsobs=[0,1.5,3,4.5,6,7.5,9.,10.5,12.,13.5,15.,16.5,18.,1.e20]
#        levelserr=[0,.25,.5,.75,1.,1.25,1.5,1.75,2.,2.25,2.5,2.75,1.e20]
##         ulevelserr=[0,.4,.8,1.2,1.6,2.,2.4,2.8,3.2,3.6,4.,4.4,1.e20]
##         ulevelserr = [0,5,10,15,20,25,30,35,40,45,50,60,70]
        ulevelserr=[0,.5,1.,1.5,2.,2.5,3.,3.5,4.,1.e20]
    else:
        ulevelsobs= [-1.e20,250,255,260,265,270,275,280,285,290,295,300,1.e20]
        ulevelsobs=[-1.e20,-20., -15., -10., -5., 0., 5., 10, 15., 20., 25.,30.,1.e20]
##     contourlevs=[200, 210, 220, 230, 240, 250, 260, 270, 280, 290, 300, 310, 320]
        contourlevs=[200, 208, 216, 224, 232, 240, 248, 256, 262, 268, 276, 284, 292, 300, 308, 316]
        contourlevs=[-72, -64, -56, -48, -40, -32, -24, -16, -8, 0, 8, 16, 24, 32, 40, 48]
        ulevels= [-1.e20,-5,-4,-3,-2,-1,0,1,2,3,4,5,1.e20]
##     ulevels = [-1.e20, -50, -40, -30, -20, -10, 0, 10, 20, 30, 40, 50]
##     ulevelserr= [0.,.5,1.,1.5,2.,2.5,3.,3.5,4.,4.5,5.,5.5,1.E20]
        ulevelserr= [0.,1.,2., 3., 4., 5., 6., 7., 8., 1.E20]
  
elif struct.var=='ts':
    user_spec_levels=True
##     ulevelsobs= [-1.e20,273., 276., 279., 282., 285., 288., 291., 294., 297., 300.,1.e20]
##     contourlevs=[270, 273., 276., 279., 282., 285., 288., 291., 294., 297., 300., 303., 306., 309.]
    ulevelsobs= [-1.e20, 0., 3., 6., 9., 12., 15., 18., 21., 24., 27., 1.e20]
    contourlevs=[-3., 0., 3., 6., 9., 12., 15., 18., 21., 24., 27., 30., 33., 36.]
    ulevels= [-1.e20,-5,-4,-3,-2,-1,0,1,2,3,4,5,1.e20]
    ulevelserr= [0.,0.5, 1., 1.5, 2., 2.5, 3., 3.5, 4., 4.5, 5., 5.5, 1.E20]
##     ecolors=range(208,220)
    
elif struct.var=='so':
    user_spec_levels=True
    ulevelsobs= [-1.e20, 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38., 1.e20]
    contourlevs=[26,27,28,29,30,31,32,33,34,35,36,37,38,39, 40]
    ulevels= [-1.e20, -2.5, -2., -1.5, -1., -.5, 0., .5, 1., 1.5, 2., 2.5, 1.E20]
    ulevelserr= [0.,.2, .4, .6, .8, 1., 1.2, 1.4, 1.6, 1.8, 2., 2.2, 1.E20]
##     ecolors=range(208,220)

elif var=='pr':
    user_spec_levels=True
    ulevels=[-1.e20,-5,-4,-3,-2,-1,0,1,2,3,4,5,1.e20]
    contourlevs=[1, 2, 4, 8, 16, 32]
    ulevelsobs=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 1.e20]
    ulevelserr=[0., .5, 1, 1.5, 2, 2.5, 3, 3.5, 4, 4.5, 5, 1.e20]
    colors=range(208,220)
    ecolors=colors
    
    
elif var=='rsut':
    user_spec_levels=True
##     ulevels=[-1.e20,-100, -80, -60, -40, -20, 0, 20, 40, 60, 80, 100,1.e20]
##     ulevelsobs=[0, 20, 40, 60, 80, 100, 120, 140, 160, 180, 200, 1.e20]
##     ulevelserr=[0., 10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 1.e20]
    ulevels=[-1.e20,-50, -40, -30, -20, -10, 0, 10, 20, 30, 40, 50, 1.e20]
    ulevelsobs=[0, 20, 40, 60, 80, 100, 120, 140, 160, 180, 200, 1.e20]
    ulevelserr=[0., 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55,  1.e20]
    
elif var=='rlutcs':
    user_spec_levels=True
##     ulevels=[-1.e20,-100, -80, -60, -40, -20, 0, 20, 40, 60, 80, 100,1.e20]
##     ulevelsobs=[0, 20, 40, 60, 80, 100, 120, 140, 160, 180, 200, 1.e20]
##     ulevelserr=[0., 10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 1.e20]
    ulevels=[-1.e20,-50, -40, -30, -20, -10, 0, 10, 20, 30, 40, 50, 1.e20]
    ulevelsobs=[0,5,10,15,20,25,30,35,40,45,50,55,1.e20]
    ulevelserr=[0., 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55,  1.e20]
    
elif var=='rsutcs':
    user_spec_levels=True
##     ulevels=[-1.e20,-100, -80, -60, -40, -20, 0, 20, 40, 60, 80, 100,1.e20]
##     ulevelsobs=[0, 20, 40, 60, 80, 100, 120, 140, 160, 180, 200, 1.e20]
##     ulevelserr=[0., 10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 1.e20]
    ulevels=[-1.e20,-50, -40, -30, -20, -10, 0, 10, 20, 30, 40, 50, 1.e20]
    ulevelsobs=[-1.e20,-150, -120, -90, -60, -30, 0, 30, 60, 90, 120, 150, 1.e20]
    ulevelserr=[0., 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55,  1.e20]
    
if user_spec_levels and not diff: ulevels=ulevelsobs

if stat=='correl':
    user_spec_levels=True
    ulevels = [-1.e20,.1, .2, .3,.4,.5,.6,.7,.8,.9,.95,.99, 1.]
##     ulevelserr = [0,.1,.2,.3,.4,.5,.6,.7,.8,.9,1.e20]


### NO CHANGES AFTER HERE

mods=models.keys()


C=Multi(nrows=4,ncols=3)
C.legend.direction='horizontal'

vardict=dictionaries.variables[struct.var]
graph = vardict.get('graphics',None)
if graph is not None:
    graph=graph.get('ipcc',None)
    
obs=vardict[ref]

try:
    graphics_scaling=obs['graphics_scaling']
    graphics_units=obs['graphics_units']
except:
    graphics_scaling=1.0
    graphics_units=obs['units']

obs_scaling=graphics_scaling
if stat=='correl':
    graphics_scaling=1

print 'graphics scaling = ', graphics_scaling
print 'graphics units = ', graphics_units

if stat=='correl':
    statis=' ('+graphics_units+') - Correlation over Time with '+obs['name']
elif stat=='std':
    statis=': Standard Deviation over Time'
    if diff:
        statis+=', Difference from '+obs['name']
elif diff:
    statis=' Difference from '+obs['name']
else:
    statis=''
            
title=obs['title']+statis

if stat !=  'correl': title = title+' ('+graphics_units+')'

obsnm=obs['name']
mask=obs['mask']
True
print 'reading ', obs['climatology']['file']
f=cdms.open(obs['climatology']['file'])
obs=f(obs['var'])
f.close()
if mask_threshold is not False:
    if mask_threshold[1]==-1:
        obs=MV.masked_less(obs,mask_threshold[0])
    elif mask_threshold[1]==1:
        obs=MV.masked_greater(obs,mask_threshold[0])
    elif mask_threshold[1]==0.:
        obs=MV.masked_equal(obs,mask_threshold[0])
    else:
        raise 'Error, mask threshold value 1 must be -1,0, or 1'
        
        
if masklnd:
    print mask
    if mask['file']!='':
        lat=obs.getLatitude()
        lon=obs.getLongitude()
        print 'reading ', mask['file']
        f=cdms.open(mask['file'])
        mask=f(mask['var'],latitude=(lat[0],lat[-1]),longitude=(lon[0],lon[-1]),squeeze=1)
        f.close()
        print genutil.minmax(mask)
        while mask.rank()>2:
            mask=MV.average(mask)
    else:
        mask =  None
else:
    mask=None

print 'struct.var = ', struct.var

if struct.var=='tasm':
    obs=obs+273.15
elif struct.var=='so':
    obs=obs(level=0,squeeze=1)
elif var=='rsut':
    ax=obs.getAxisList()
    # replace missing values with 0.0
    obs.set_fill_value(0.0)
    tmp=obs.filled()
    obs=MV.masked_array(tmp, axes=ax)
    del tmp
 

    
if var2 is not None:
    vardict=dictionaries.variables[var2]
    Obs=vardict[ref]
    f=cdms.open(Obs['climatology']['file'])
    obs=obs - f(Obs['var'])
    f.close()
    title=title2+' ('+graphics_units+')'+statis
    
if var=='so':
    title='Surface '+title

if snm != "":
    title=snm+' '+title

 
elif stat=='correl':
    pass
elif stat=='std':
    obs=genutil.statistics.std(obs)
    print 'Stded'
else:
##     obs=MV.average(obs)
    if struct.var!='so':
        obs=getseason(obs,snm) ## snm="" means annual average

    
if masklnd:
    if mask is not None:
        obs=MV.masked_where(mask,obs)

mean=MV.zeros(obs.shape)
err=MV.zeros(obs.shape)

if diff or stat=='correl':
    tobs=C.get(legend='local',original='orig')
else:
    tobs=C.get(original='orig')

tmean=C.get(original='orig')
terr=C.get(legend='local',original='orig')

models=Models.keys()
models.sort()
nmod=len(models)

bg=1

ppage=-1
x=[vcs.init(),vcs.init(),vcs.init(),vcs.init()]

ngood=0

templates={}
iso=x[0].createisofill('map')

if graph is not None:
    if not user_spec_levels:
        try:
            levels    = graph['map']['levelsd']
            levelsobs = graph['map']['levels']
            levelserr = graph['map']['levelsrms']
            if not diff: levels=levelsobs
        except:
            user_spec_levels=True
    if user_spec_levels:
        levels = ulevels
        levelsobs=ulevelsobs
        levelserr=ulevelserr
        
iso.levels=levels

if diff:
    iso.fillareacolors=vcs.getcolors(iso.levels,colors=dcolors)
else:
    iso.fillareacolors=vcs.getcolors(iso.levels,colors=colors)

iso.missing=252

isoobs=x[0].createisofill('obs','map')
isoobs.levels=levelsobs
isoobs.fillareacolors=vcs.getcolors(isoobs.levels,colors=colors)
isoobs.missing=252

if var2 is not None:
    var2nm='-'+var2
else:
    var2nm=''
if snm!="":
    snmtitle='_'+snm
else:
    snmtitle=''

copystart=struct.start

for i in range(nmod):
    mod=models[i]
    accr=Models[mod]['accr']
##     print mod,accr
    I,J = divmod(i,3)
    page,I=divmod(I,3)
    if page==0:
        t=C.get(J,I+1,original='orig')
        t.legend.priority=1
        templates[t.name]=t
    else:
        name=str(J)+'_x_'+str(I+1)
        t=templates[name]
    if page!=ppage:
        ppage=page
        obs.id=obsnm
##     print i,mod,page,I,J

    struct.start=copystart
    fnm,clim_flg=getfnm(struct,accr)

    if not os.path.exists(fnm):
        print '--',fnm
        tt=x[page].createtext(mod)
        tt.x=[(t.data.x2+t.data.x1)/2.]
        tt.y=[(t.data.y2+t.data.y1)/2.]
        tt.halign='center'
        tt.string=[mod]
        lc=x[page].getline('continents')
        lc.width=continent_line
        x[page].plot(tt,continents=continents,bg=bg)
        continue
    
    print '++',fnm
    f=cdms.open(fnm)
    if struct.var=='so':
        var=f(struct.var,level=(0,80),squeeze=1)[:,0]
    else:
        var=f(struct.var)
    if mask_threshold is not False:
        if mask_threshold[1]==-1:
            var=MV.masked_less(var,mask_threshold[0])
        elif mask_threshold[1]==1:
            var=MV.masked_greater(var,mask_threshold[0])
        elif mask_threshold[1]==0.:
            var=MV.masked_equal(var,mask_threshold[0])
        
    
    f.close()

    if var2 is not None:
        varsv=struct.var
        struct.var=var2
        fnm,clim_flg=getfnm(struct,accr)
        f=cdms.open(fnm)
        var=var - f(struct.var)
        f.close()
        struct.var=varsv
        
        
    if stat=='correl':
        statis='_correlation'
    elif stat=='std':
        var=genutil.statistics.std(var)
        statis='_std'
    else:
##         var=MV.average(var)
        var=getseason(var,snm) ## snm="" means average

        statis=''
    if diff:
        statis=statis+'_diff'

    var=var.regrid(obs.getGrid())

    if stat=='correl':
        mean=mean+var
        var=genutil.statistics.correlation(var,obs)  
    else:
        if diff: var=var-obs
        mean=mean+var
        #   for percent difference
##         var=100.*var/obs

    var.id=mod
    err=err+var*var
    lc=x[page].getline('continents')
    lc.width=continent_line
    tmp=var*graphics_scaling+diff_offset
    tmp.id=mod
    x[page].plot(tmp,t,iso,continents=continents,bg=bg)
    del tmp

    fnmps='../Out/'+struct.var+var2nm+'_'+accr+statis+snmtitle+'.ps'
    lc=x[-1].getline('continents')
    lc.width=continent_line
    tmp=var*graphics_scaling+diff_offset
    tmp.id=mod
    x[-1].plot(tmp,iso,continents=continents,bg=bg)
    del tmp
    x[-1].postscript(fnmps)
    x[-1].clear()
    if bg==0 : x[-1].close()
    ngood+=1
    
mean=mean/ngood

## mean = 100.*mean/obs

if stat == 'correl':
    ax=obs.getAxisList()
    mean.setAxisList(ax)
    mean=genutil.statistics.correlation(mean,obs)
    nm=obs.idx[-1].plot(tmp,iso,continents=continents,bg=bg)

    obs=MV.average(obs)
    obs.id=nm
else:
    err=MV.sqrt(err/ngood)
    ax=obs.getAxisList()
    mean.setAxisList(ax)
    err.setAxisList(ax)

mean.id='Mean Model'
err.id='Typical Error'
isoerr=x[0].createisofill('err','map')
isoerr.levels=levelserr
isoerr.fillareacolors=vcs.getcolors(isoerr.levels,colors=ecolors)
isoerr.missing=252

fnmps='../Out/'+struct.var+var2nm+'_mean'+statis+snmtitle+'.ps'
lc=x[-1].getline('continents')
lc.width=continent_line

tmp=mean*graphics_scaling+diff_offset
tmp.id=mean.id
x[-1].portrait()
if contourlevs is not None:
    isol.levels=contourlevs
else:
    isol.levels=levelsobs
    print 'levelsobs = ', levelsobs
isol.datawc_y1=iso.datawc_y1
isol.datawc_y2=iso.datawc_y2
isol.datawc_x1=iso.datawc_x1
isol.datawc_x2=iso.datawc_x2
meantmpl.legend.y1=.23
meantmpl.legend.y2=.245


x[-1].plot(tmp,iso,meantmpl,continents=continents,bg=bg,ratio='0.5t')
if contourlines:
    tmp=obs*graphics_scaling+offset
    tmp.id=obs.id
    x[-1].plot(tmp,isol,meantmplnolg,continents=continents,bg=bg,ratio='0.5t')
del tmp
## x[-1].postscript(fnmps)
x[-1].postscript(fnmps,'r','p')
x[-1].clear()
if bg==0 : x[-1].close()
## if correl or (std and not std_diff):
##     pass
## else:
if diff:
    fnmps='../Out/'+struct.var+var2nm+'_err'+statis+snmtitle+'.ps'
    lc=x[-1].getline('continents')
    lc.width=continent_line
    tmp = err*graphics_scaling
    tmp.id=err.id
    x[-1].plot(tmp,isoerr,meantmpl,continents=continents,bg=bg,ratio='0.5t')
    del tmp
    x[-1].postscript(fnmps,'r','p')
    x[-1].clear()
    if bg==0 : x[-1].close()    
fnmps='../Out/'+struct.var+var2nm+'_obs'+statis+snmtitle+'.ps'

lc=x[-1].getline('continents')
lc.width=continent_line
tmp=obs*obs_scaling+offset
tmp.id=obs.id
## if diff:
x[-1].plot(tmp,isoobs,meantmpl,continents=continents,bg=bg,ratio='0.5t')
x[-1].postscript(fnmps,'r','p')
## else:
##     x[-1].landscape()
##     x[-1].plot(tmp,isoobs,continents=continents,bg=bg)
##     x[-1].postscript(fnmps)
del tmp
x[-1].clear()
if bg==0 : x[-1].close()

x[-1].landscape()

tit.string=[title]

for p in range(page+1):
    fnmps='../Out/'+struct.var+var2nm+'_page_'+str(p+1)+statis+snmtitle+'.ps'
    print 'dumping page:',p+1,fnmps
    lc=x[p].getline('continents')
    lc.width=continent_line
    x[p].plot(tit,bg=bg)
    tmp=mean*graphics_scaling+diff_offset
    tmp.id=mean.id
    x[p].plot(tmp,tmean,iso,continents=continents,bg=bg)
    del tmp
    if diff:
        lc=x[p].getline('continents')
        lc.width=continent_line
        tmp = err*graphics_scaling
        tmp.id=err.id
        x[p].plot(tmp,terr, isoerr,continents=continents,bg=bg)
        del tmp
    lc=x[p].getline('continents')
    lc.width=continent_line
    tmp=obs*obs_scaling+offset
    tmp.id=obs.id
    x[p].plot(tmp,isoobs,tobs,bg=bg,continents=continents)
    del tmp
    x[p].postscript(fnmps)
```
and here's the colormap used:
```
C_pcmdi(
99,99,99,
0,0,0,
87,88,87,
24,24,24,
99,99,99,
99,99,0,
0,0,99,
0,0,99,
0,0,99,
0,11,99,
0,11,99,
0,11,99,
0,11,99,
0,22,99,
0,22,99,
0,24,99,
84,84,84,
99,99,99,
99,99,99,
99,99,99,
99,99,99,
99,99,99,
99,99,99,
99,99,99,
99,99,99,
99,99,99,
99,99,99,
99,99,99,
99,99,99,
99,99,99,
99,99,99,
99,99,99,
99,48,0,
99,62,0,
99,81,0,
99,99,24,
68,99,99,
35,88,99,
0,77,99,
0,0,99,
71,40,99,
99,0,99,
99,99,99,
99,99,99,
99,99,99,
99,99,99,
99,99,99,
99,99,99,
97,37,99,
68,57,99,
0,0,99,
0,66,99,
51,95,99,
77,99,99,
99,99,64,
99,82,24,
99,62,24,
99,46,22,
99,0,0,
51,0,0,
99,99,99,
99,99,99,
99,99,99,
99,99,99,
84,11,99,
62,37,99,
0,0,99,
0,66,99,
37,92,99,
68,99,99,
99,99,24,
99,82,24,
99,62,24,
99,46,22,
99,0,0,
51,0,0,
99,99,99,
99,99,99,
99,99,99,
99,99,99,
44,11,62,
11,11,84,
24,48,90,
40,64,90,
55,81,94,
68,92,99,
99,82,81,
99,70,68,
97,44,44,
99,24,24,
71,0,0,
37,0,0,
99,99,99,
99,99,99,
99,99,99,
99,99,99,
0,11,99,
0,40,99,
20,60,99,
40,80,99,
60,93,99,
80,99,99,
99,99,80,
99,93,60,
99,80,40,
99,60,20,
99,40,0,
99,11,0,
99,99,99,
99,99,99,
99,99,99,
99,99,99,
44,11,62,
0,40,99,
20,60,99,
40,80,99,
60,93,99,
80,99,99,
99,99,80,
99,93,60,
99,80,40,
99,60,20,
99,40,11,
99,11,0,
99,99,99,
99,99,99,
99,99,99,
99,99,99,
44,11,62,
0,40,99,
20,60,99,
40,80,99,
60,93,99,
80,99,99,
99,93,60,
99,80,40,
99,60,20,
99,40,11,
99,0,0,
51,0,0,
99,99,99,
99,99,99,
99,99,99,
99,99,99,
44,11,62,
0,40,99,
20,60,99,
40,80,99,
60,93,99,
80,99,99,
99,93,60,
99,80,40,
99,60,20,
99,46,22,
99,0,0,
51,0,0,
99,99,99,
99,99,99,
99,99,99,
99,99,99,
24,0,94,
26,51,94,
40,70,94,
55,81,94,
68,92,99,
99,82,81,
99,70,68,
97,44,44,
99,24,24,
71,0,0,
99,99,99,
99,99,99,
99,99,99,
99,99,99,
99,99,99,
99,99,99,
24,2,100,
26,51,94,
40,70,94,
55,81,94,
68,92,99,
99,82,81,
99,70,68,
97,44,44,
99,24,24,
71,0,0,
99,99,99,
99,99,99,
99,99,99,
99,99,99,
99,99,99,
99,99,99,
99,99,99,
99,99,99,
99,99,99,
99,99,99,
99,99,99,
99,99,99,
99,99,99,
99,99,99,
99,99,99,
99,99,99,
99,99,99,
99,99,99,
99,99,99,
99,99,99,
99,99,99,
99,99,99,
99,93,60,
99,80,40,
99,60,20,
99,40,11,
99,0,0,
51,0,0,
44,11,62,
0,40,99,
20,60,99,
40,80,99,
60,93,99,
80,99,99,
99,99,99,
99,99,99,
99,99,99,
99,99,99,
99,99,99,
99,99,99,
99,99,99,
99,99,99,
99,99,99,
99,99,99,
99,99,99,
99,99,99,
99,99,99,
99,99,99,
99,99,99,
99,99,99,
99,99,99,
99,99,99,
99,99,99,
99,99,99)
```

**Comment by durack1** [comment]
@doutriaux1 it would be great if we could pull @taylor13's colormaps into `VCS` as well so they are also available without having to locate another file somewhere.. We could potentially have a dictionary with `default` palettes, and these (and Ken's, my extras etc) could all be placed in an `auxiliary` colormap dictionary.. So be there sitting beside the `default` but not confuse a new user as you indicated was the reason why the large number of palettes was removed..

**Comment by aashish24** [comment]
+1 where is the definition of @taylor13 colormaps?

**Comment by doutriaux1** [comment]
that's what your initial.attribute file is for. I'm open to stick it as part of pmp. Or make an external, separate package with a bunch of vcs templates, colormaps, graphic methods etc..., organized by project/themes.

**Comment by doutriaux1** [comment]
@durack1 I have to balance between user that want everything in the kitchen sink and those who wants a faster more efficient vcs...

**Comment by durack1** [comment]
@doutriaux1 why fracture things out of `VCS`, it's colormaps so just put them all into the `VCS` module, rather than fragmenting them around between UV-CDAT, the PMP, CDP or whatever..

**Comment by durack1** [comment]
> +1 where is the definition of @taylor13 colormaps?

@aashish24 see https://github.com/UV-CDAT/vcs/issues/238#issuecomment-326447996 above

**Comment by doutriaux1** [comment]
@durack1 because 
* it takes resources to load them in everytime
* people complained before there was too many of them and they made no sense to them

**Comment by jypeter** [comment]
@doutriaux1 btw is there a page or pdf somewhere that says what the different elements of a template are (what they are for and where there are by default on a canvas)?

I know a bunch and I do trial/error otherwise but I was trying to tell a new user about templates yesterday and having something to show to the users would be nice. I have found some of your old tutorials, but none has a page that would show where the elements are (or what they are for). A bit like the template editor

**Comment by durack1** [comment]
>    it takes resources to load them in everytime

@doutriaux1 which is the reason above (https://github.com/UV-CDAT/vcs/issues/238#issuecomment-326607345) I made the suggestion of the `auxiliary` so that they are just shipped and not loaded by default. This means that ALL the colour maps are available to a user who wants to use them, but the `default` palettes are a much smaller subset to aid efficiency.. As an aside, why is anything loaded upon startup? It would be more efficient to load as required rather than just reading everything and taking time and resources to do that..

>    people complained before there was too many of them and they made no sense to them

This is another issue, if there was comprehensive documentation (and there was some renaming of contributing colour maps) then this wouldn't be an issue

**Comment by doutriaux1** [comment]
@jypeter yes there are. I need to put thme somewhere
# VCS Template
![template_asd3](https://user-images.githubusercontent.com/2781425/29979739-8f2acb66-8efb-11e7-8d34-0cb769194dfc.jpg)
# Taylor diagrams
![taylorctl](https://user-images.githubusercontent.com/2781425/29979756-9cc4169c-8efb-11e7-8b84-7be02b099c2b.jpg)

**Comment by lee1043** [comment]
@doutriaux1  That graphic is really helpful! Thanks for sharing.

**Comment by lee1043** [comment]
Visualization of @taylor13's color maps, C_pcmdi given at https://github.com/UV-CDAT/vcs/issues/238#issuecomment-326447996

![test_taylor_cmap](https://user-images.githubusercontent.com/17091564/29991053-0eff834c-8f36-11e7-858e-6a7d29e9c9be.png)

**Comment by taylor13** [comment]
As I recall the different variants on the same color map, all contained in one file are designed for different numbers of contours.  It would be easier to to see this if you spread out each of the bands in the figure above, placing each on a new row  (so instead of a single row, 11 color rows; and I think there are some grey scale options in slots 0-40.

**Comment by jypeter** [comment]
Thanks @doutriaux1 ! That's a typical example where a nice figure is better than a notebook

**Comment by lee1043** [comment]
@taylor13 I believe below is what you suggested. Each of the bands was stretched to have 240 color levels. ```LinearSegmentedColormap``` of ```vcs``` ([details here](https://matplotlib.org/examples/pylab_examples/custom_cmap.html)) was applied. 

![test_taylor_cmap_stretch](https://user-images.githubusercontent.com/17091564/30085724-c1958722-924c-11e7-858c-29c8e4e621b9.png)

Sharing below code for future reference:

```python
import vcs, MV2
import EzTemplate
from matplotlib.colors import LinearSegmentedColormap

C_pcmdi = [
99,99,99,
0,0,0,
87,88,87,
24,24,24,
99,99,99,
99,99,0,
0,0,99,
0,0,99,
0,0,99,
0,11,99,
0,11,99,
0,11,99,
0,11,99,
0,22,99,
0,22,99,
0,24,99,
84,84,84,
99,99,99,
99,99,99,
99,99,99,
99,99,99,
99,99,99,
99,99,99,
99,99,99,
99,99,99,
99,99,99,
99,99,99,
99,99,99,
99,99,99,
99,99,99,
99,99,99,
99,99,99,
99,48,0,
99,62,0,
99,81,0,
99,99,24,
68,99,99,
35,88,99,
0,77,99,
0,0,99,
71,40,99,
99,0,99,
99,99,99,
99,99,99,
99,99,99,
99,99,99,
99,99,99,
99,99,99,
97,37,99,
68,57,99,
0,0,99,
0,66,99,
51,95,99,
77,99,99,
99,99,64,
99,82,24,
99,62,24,
99,46,22,
99,0,0,
51,0,0,
99,99,99,
99,99,99,
99,99,99,
99,99,99,
84,11,99,
62,37,99,
0,0,99,
0,66,99,
37,92,99,
68,99,99,
99,99,24,
99,82,24,
99,62,24,
99,46,22,
99,0,0,
51,0,0,
99,99,99,
99,99,99,
99,99,99,
99,99,99,
44,11,62,
11,11,84,
24,48,90,
40,64,90,
55,81,94,
68,92,99,
99,82,81,
99,70,68,
97,44,44,
99,24,24,
71,0,0,
37,0,0,
99,99,99,
99,99,99,
99,99,99,
99,99,99,
0,11,99,
0,40,99,
20,60,99,
40,80,99,
60,93,99,
80,99,99,
99,99,80,
99,93,60,
99,80,40,
99,60,20,
99,40,0,
99,11,0,
99,99,99,
99,99,99,
99,99,99,
99,99,99,
44,11,62,
0,40,99,
20,60,99,
40,80,99,
60,93,99,
80,99,99,
99,99,80,
99,93,60,
99,80,40,
99,60,20,
99,40,11,
99,11,0,
99,99,99,
99,99,99,
99,99,99,
99,99,99,
44,11,62,
0,40,99,
20,60,99,
40,80,99,
60,93,99,
80,99,99,
99,93,60,
99,80,40,
99,60,20,
99,40,11,
99,0,0,
51,0,0,
99,99,99,
99,99,99,
99,99,99,
99,99,99,
44,11,62,
0,40,99,
20,60,99,
40,80,99,
60,93,99,
80,99,99,
99,93,60,
99,80,40,
99,60,20,
99,46,22,
99,0,0,
51,0,0,
99,99,99,
99,99,99,
99,99,99,
99,99,99,
24,0,94,
26,51,94,
40,70,94,
55,81,94,
68,92,99,
99,82,81,
99,70,68,
97,44,44,
99,24,24,
71,0,0,
99,99,99,
99,99,99,
99,99,99,
99,99,99,
99,99,99,
99,99,99,
24,2,100,
26,51,94,
40,70,94,
55,81,94,
68,92,99,
99,82,81,
99,70,68,
97,44,44,
99,24,24,
71,0,0,
99,99,99,
99,99,99,
99,99,99,
99,99,99,
99,99,99,
99,99,99,
99,99,99,
99,99,99,
99,99,99,
99,99,99,
99,99,99,
99,99,99,
99,99,99,
99,99,99,
99,99,99,
99,99,99,
99,99,99,
99,99,99,
99,99,99,
99,99,99,
99,99,99,
99,99,99,
99,93,60,
99,80,40,
99,60,20,
99,40,11,
99,0,0,
51,0,0,
44,11,62,
0,40,99,
20,60,99,
40,80,99,
60,93,99,
80,99,99,
99,99,99,
99,99,99,
99,99,99,
99,99,99,
99,99,99,
99,99,99,
99,99,99,
99,99,99,
99,99,99,
99,99,99,
99,99,99,
99,99,99,
99,99,99,
99,99,99,
99,99,99,
99,99,99,
99,99,99,
99,99,99,
99,99,99,
99,99,99 ]

R = []
G = []
B = []

for i in range(0,720,3):
  R.append(C_pcmdi[i])
for i in range(1,720,3):
  G.append(C_pcmdi[i])
for i in range(2,720,3):
  B.append(C_pcmdi[i])

vcs.utils.defaultColorsRange = range(16,240)
v = vcs.init(geometry={"width":1000,"height":500}, bg=1) # Create a vcs Canvas
cmap = v.createcolormap('tylor13_all_bands', 'default') # Create a colormap

labels = []

for i in range(0,240):
  cmap.setcolorcell(i,R[i],G[i],B[i],100)

  if i > 0 and i < 240: 
    if R[i]!=99 or G[i]!=99 or B[i]!=99:
      if R[i-1]==99 and G[i-1]==99 and B[i-1]==99:
        labels.append(i)
      if R[i+1]==99 and G[i+1]==99 and B[i+1]==99:
        labels.append(i+1)

print labels

#####################################################################

def SpreadBand(i1,i2,cm_name):

  # Append colors in each as tuples
  colors = []
  for i in range(i1,i2):
    colors.append((R[i]/100.,G[i]/100.,B[i]/100.))

  # Create the colormap (Matplotlib)
  cmap_name = 'my _list'
  cm = LinearSegmentedColormap.from_list(cmap_name, colors, N=240)

  # Convert Matplotlib colormap to VCS one
  vcs_cmap = vcs.colors.matplotlib2vcs(cm, vcs_name=cm_name)

  return(vcs_cmap)

#####################################################################

cmlst = []
cmlst.append(cmap) # Original one at the beginning

for i in range(0,len(labels),2):
  i1 = labels[i]
  i2 = labels[i+1]
  cm_name = 'band_'+str(i/2) 
  cmlst.append(SpreadBand(i1,i2,cm_name))


#####################################################################

a = []

num_levels = 240

for i in range(0,num_levels):
  a.append(i/float(num_levels))

for i in range(0,num_levels):
  a.append(i/float(num_levels))

a = MV2.array(a)
a = MV2.reshape(a, (-1,num_levels))

v = vcs.init(geometry={"width":600,"height":1200}, bg=1)

cmlst_num = len(cmlst)
print len(cmlst)

T = vcs.createtemplate()
T.blank(['title','mean','min','max','dataname','crdate','crtime',
         'units','zvalue','tvalue','xunits','yunits','xname','yname', 'legend'])

M = EzTemplate.Multi(template=T, rows=cmlst_num, columns=1)
M.margins.top = 0.05
M.margins.bottom = 0.05
M.margins.left = 0.3
M.margins.right = 0.05
M.spacing.vertical= 0.005

plot_title = v.createtext()
plot_title.string = 'Colormaps given by Taylor for VCS'
plot_title.height = 15
plot_title.halign = 'center'
plot_title.valign = 'bottom'
plot_title.x = 0.5
plot_title.y = 1 - M.margins.top + (0.01)
v.plot(plot_title, T)

for i in range(0, cmlst_num):
    box = v.createboxfill()
    box.color_2 = 240
    box.xticlabels('','') # Hide x-axis tick labels
    box.yticlabels('','') # Hide y-axis tick labels
    box.colormap = cmlst[i]

    #if i == 0:
    #  xticlabels = {}
    #  for x in labels:
    #    xticlabels[x] = str(x) 
    #  box.xticlabels1 = xticlabels

    t = M.get(row=i, column=0, legend='none')
    t.blank(['legend'])

    v.plot(a, t, box, bg=1)

    subplot_title = vcs.createtext()
    subplot_title.string = box.colormap
    subplot_title.x = 0.01
    subplot_title.y = (t.box1.y1 + t.box1.y2) / 2.
    subplot_title.height = 10
    subplot_title.halign = 'left'
    subplot_title.valign = 'half'
    subplot_title.color = 'black'
    v.plot(subplot_title, t)

    v.removeobject(box)
    v.removeobject(subplot_title)
    print box.colormap

v.png('test_taylor_cmap_stretch.png')
```

**Comment by durack1** [comment]
@lee1043 I took your code above and wedged it into a file, just so it's easy to scroll through the various comments (the code blocks take a while to get through!) If you're happy with the edit, do you want to purge your code block above?

**Comment by durack1** [comment]
@lee1043 and nice work on these palettes too! @taylor13 thanks for your tireless work back in the dark ages of VC-DAT too!

**Comment by lee1043** [comment]
@durack1 good to learn that I can attach the ascii file. Thanks!

**Comment by durack1** [comment]
@lee1043 you can also purge your own (and others) comments, so after imparting github wisdom I shall now delete my redundant comments (this, and above)

**Comment by lee1043** [comment]
@taylor13 Thanks for clarifying what you were looking for and here it is:

![test_taylor_cmap_discrete](https://user-images.githubusercontent.com/17091564/30088237-f084e980-9259-11e7-912d-e0115523ea2f.png)

Plotting code:
[taylor_colormaps_discrete.py.txt](https://github.com/UV-CDAT/vcs/files/1279301/taylor_colormaps_discrete.py.txt)

**Comment by jypeter** [comment]
Nice!

@doutriaux1  are the last 16 color indices still _protected_ so that you are sure to always get the same 16 basic colors for lines, text, etc? Because I tried to use red and green (indices 253 and 254 or something like that) when using _bl_to_darkred_, but the colors I got were more yellow-orange, like in the middle of bl_to_darkred

**Comment by doutriaux1** [comment]
@jypeter no since `2.10` there's no more protected colors. I know it's a pain for older colormaps. This might get better in `3.0` we have ideas for colormaps.

**Comment by lee1043** [comment]
@doutriaux1 Could you remind me what was the one single line commend to bring all matplotlib colormaps in?

**Comment by doutriaux1** [comment]
vcs.utils.loadmatplotlibcolormaps()

**Comment by lee1043** [comment]
@doutriaux1 Thanks!
